import axios from "axios";
import Head from "next/head";
import React, { useEffect, useRef } from "react";
import { FormUnicorn } from "../components/FormUnicorn";
import { Unicorn } from "../models";
import useSWR, { mutate } from 'swr';

export default function Home() {
  const {data } = useSWR('fetch',()=>axios.get<Unicorn[]>("https://unicorn-api.vercel.app/api/unicorns"));
  const unicorns: Unicorn[] = data?.data ?? [];
  const ref = useRef<HTMLHeadingElement>(null);
  const onSubmit = async (payload: Unicorn) => {
    await axios.post(
      "https://unicorn-api.vercel.app/api/unicorns",
      payload
      );
    ref.current.scrollIntoView({behavior: 'smooth'});
    mutate('fetch');
  }

  return (
    <div>
      <Head>
        <title>Create Unicorn App</title>
        <meta name="description" content="Generated by Netlight." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 space-y-4">
        <h1 className="text-6xl text-center">Bring your unicorn to life</h1>
        <h2 className="text-3xl text-center">The unicorn is feeling a little bit grey, make it feel colorful again!</h2>
        <div className="max-w-prose mx-auto">
        <FormUnicorn id="new" onSubmit={onSubmit}/>
        </div>
        <h2 id="herd-title" ref={ref} className="text-3xl text-center">The lively herd</h2>
        <div className="sm:grid grid-cols-4 gap-4">
        {unicorns.map(({ _id, ...rest }) => (
          <FormUnicorn key={_id} id={_id} initialState={rest} disabled />
        ))}
        </div>
      </main>
    </div>
  );
}
